### ISSUE TITLE
The link to input image guidelines does not work

### ISSUE THREAD

**Issue by leebachacko** [junlabucsd/napari-mm3#27]
When I click on the link to "input image guidelines", I get an Error 404 message.

**Comment by ahirsharan** [comment]
Thanks for poiting it out. I have fixed the broken link. I hope it works for you now.

**Comment by leebachacko** [comment]
Thank you!

**Comment by leebachacko** [comment]
> Thanks for poiting it out. I have fixed the broken link. I hope it works for you now.

Hi ahirsharan, the link still does not seem to work, unfortunately. Could you please share the link here?

**Comment by ahirsharan** [comment]
It seems there were two broken links with the same name of "input image guidelines" in section a and section f. I earlier fixed the one in f. I have also fixed the remaining one. Can you confirm if it works now?

**Comment by leebachacko** [comment]
Hi Gursharan Ahir,

The two links I checked were the following and both of them do not seem to
be working for me.

1. "*Input image guidelines"* under "*preprocessing"* here -
https://github.com/junlabucsd/napari-mm3

2. "*Input image guidelines"* under "*preprocessing"* here-
https://pypi.org/project/napari-mm3/

Not sure if there was some other place I was supposed to check. if so,
could you please share that link with me?

Thank you.

Warm regards,
Leeba



Thank you.
Warm regards,
Leeba

**Comment by leebachacko** [comment]
> It seems there were two broken links with the same name of "input image guidelines" in section a and section f. I earlier fixed the one in f. I have also fixed the remaining one. Can you confirm if it works now?

I just tried it with the Chrome browser and it works now. Thank you for fixing the link! Both links do not seem to open with Safari. 

Also, the input image guidelines link that is on this page https://pypi.org/project/napari-mm3/ does not work on the Chrome browser either.

**Comment by michaels10** [comment]
Hi Leeba,
Sorry for the long delay! I just double checked this, and it seems that the links work in Chrome, Firefox, and Safari, both on pypi, and on github. Gonna go ahead and close this one.

Best,
Michael S

**Comment by leebachacko** [comment]
It does. Thank you!
