### ISSUE TITLE
Issues related to napari-mm3 installation

### ISSUE THREAD

**Issue by GaoCheng22** [junlabucsd/napari-mm3#38]
After installtion of napari-mm3, i encountered two difficulties.

1. It reported ModuleNotFoundError: No module named 'javabridge' after running TIFFConverter, and during the installation of javabridge, it reported that cl.exe' failed with exit code 2
2. It reported IndexError: list index out of range after running other function.

I am here to ask for your help, thank you very much!!!

**Comment by rthiermann** [comment]
Hi,

Unfortunately it sounds like these are issues with your javabridge installation, so you may be better served by asking on the javabridge repository or StackOverflow.

What format is your raw data in? Right now we do rely on Bioformats (which needs javabridge) to convert all file formats other than .nd2 or tiff, but if you can convert your data to one of these formats you should not need it.

**Comment by GaoCheng22** [comment]
Thank you very much!
My raw data format is TIFF, and i still confused about 'IndexError: list index out of range'

**Comment by rthiermann** [comment]
Can you share the stack trace for the error you got? (i.e. which line specifically caused the IndexError).

Make sure that you have "image_source" set to "Bioformats/other" in the Compile widget. The widget expects the tiff files to have a format ending in t000xy00c0.tiff with the time point t, FOV xy and color channel c.

If you want, you can share a sample of your raw data with me and I can try to reproduce the error.

**Comment by GaoCheng22** [comment]
Thank you very much！I tried reinstall my python and napari-mm3 can be called successfully.
But it still report an error when I try to run the compile step.
EmitLoopError:
While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in callback 'napari_mm3._deriving_widgets.Compile._save_settings'.
The args passed to the callback were: (False,)
This is not a bug in psygnal.  See 'AttributeError' above for details.

**Comment by rthiermann** [comment]
Can you share the full stack trace you get? (including initial 'AttributeError')

**Comment by rthiermann** [comment]
We had a similar bug to what you describe a few months ago but it should be resolved in the most recent version of the code - make sure you are pulling the current version from Github (git clone https://github.com/junlabucsd/napari-mm3.git), not downloading from PyPI or napari-hub.

**Comment by GaoCheng22** [comment]
Thank you very much！
I tried to install the current version from Github, but it still exist some problem.
I wonder if napari-mm3 supports Windows 64？

**Comment by rthiermann** [comment]
Sorry that you're still having trouble! Yes, it's been tested on Windows 10 (64 bit). Can you share the errors you get?

**Comment by michaels10** [comment]
Hi all -- I got around to fixing around some of the dependency issues that I saw people having. I've replaced nd2reader with nd2, switch to a conda-based environment install, and limited the numpy version (2.0 has backwards compatibility issues).

Also notably, conda uses mamba's solver now, so those special instructions are also gone.

To update, try pulling and running 'conda install nd2'; after that, it should work as before.

Unless there are further issues, marking as closed.
